version: '3.8'

services:
  web_frontend:
    build: ./frontend
    container_name: frontend_app
    image: root938/test-frontend-app
    ports:
      - "3000:80"   # Host 3000 -> Container 80 (Nginx)
    restart: always
    networks:
      - my_app

  web_backend:
    build: ./backend
    container_name: backend_app
    image: root938/test-backend-app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - pg_db
      - mg_db
    networks:
      - my_app

  pg_db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fullstackdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_app

  mg_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fullstackapp
    volumes:
      - mongo_data:/data/db
    networks:
      - my_app

volumes:
  pgdata:
  mongo_data:

networks:
  my_app:
