
kind: ConfigMap
apiVersion: v1
metadata: 
   name: mongo-configmap 
   namespace: my-app
data:
  MONGO_INITDB_DATABASE: fullstackapp

---

kind: Deployment
apiVersion: apps/v1
metadata:
    name: mongo-deployment
    namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
         - configMapRef:
             name: mongo-configmap
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: Service
apiVersion: v1
metadata:
   name: mongo-service 
   namespace: my-app
spec: 
    selector:
      app: mongo
    ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017